
USE spread;




-- ----------------------------
-- Records of spread_area
-- ----------------------------
INSERT INTO `spread_area` VALUES ('0', '0', '全国', 'quanguo');
INSERT INTO `spread_area` VALUES ('1', '0', '北京', 'beijing');
INSERT INTO `spread_area` VALUES ('2', '0', '上海', 'shanghai');
INSERT INTO `spread_area` VALUES ('3', '0', '天津', 'tianjin');
INSERT INTO `spread_area` VALUES ('4', '0', '重庆', 'chongqing');
INSERT INTO `spread_area` VALUES ('5', '0', '河北', 'hebei');
INSERT INTO `spread_area` VALUES ('6', '0', '山西', 'shanxi2');
INSERT INTO `spread_area` VALUES ('7', '0', '内蒙古', 'neimenggu');
INSERT INTO `spread_area` VALUES ('8', '0', '辽宁', 'liaoning');
INSERT INTO `spread_area` VALUES ('9', '0', '吉林', 'jilin');
INSERT INTO `spread_area` VALUES ('10', '0', '黑龙江', 'heilongjiang');
INSERT INTO `spread_area` VALUES ('11', '0', '江苏', 'jiangsu');
INSERT INTO `spread_area` VALUES ('12', '0', '浙江', 'zhejiang');
INSERT INTO `spread_area` VALUES ('13', '0', '安徽', 'anhui');
INSERT INTO `spread_area` VALUES ('14', '0', '福建', 'fujian');
INSERT INTO `spread_area` VALUES ('15', '0', '江西', 'jiangxi');
INSERT INTO `spread_area` VALUES ('16', '0', '山东', 'shandong');
INSERT INTO `spread_area` VALUES ('17', '0', '河南', 'henan');
INSERT INTO `spread_area` VALUES ('18', '0', '湖北', 'hubei');
INSERT INTO `spread_area` VALUES ('19', '0', '湖南', 'hunan');
INSERT INTO `spread_area` VALUES ('20', '0', '广东', 'guangdong');
INSERT INTO `spread_area` VALUES ('21', '0', '广西', 'guangxi');
INSERT INTO `spread_area` VALUES ('22', '0', '海南', 'hainan');
INSERT INTO `spread_area` VALUES ('23', '0', '四川', 'sichuan');
INSERT INTO `spread_area` VALUES ('24', '0', '贵州', 'guizhou');
INSERT INTO `spread_area` VALUES ('25', '0', '云南', 'yunnan');
INSERT INTO `spread_area` VALUES ('27', '0', '陕西', 'shanxi');
INSERT INTO `spread_area` VALUES ('28', '0', '甘肃', 'gansu');
INSERT INTO `spread_area` VALUES ('29', '0', '宁夏', 'ningxia');
INSERT INTO `spread_area` VALUES ('30', '0', '青海', 'qinghai');
INSERT INTO `spread_area` VALUES ('31', '0', '新疆', 'xinjiang');
INSERT INTO `spread_area` VALUES ('32', '0', '西藏', 'xizang');
INSERT INTO `spread_area` VALUES ('33', '0', '台湾', 'taiwan');
INSERT INTO `spread_area` VALUES ('34', '0', '香港', 'xianggang');
INSERT INTO `spread_area` VALUES ('35', '0', '澳门', 'aomen');
INSERT INTO `spread_area` VALUES ('184', '12', '宁波', 'ningbo');
INSERT INTO `spread_area` VALUES ('185', '2', '普陀', 'putuo');
INSERT INTO `spread_area` VALUES ('186', '1', '丰台', 'fengtai');
INSERT INTO `spread_area` VALUES ('187', '20', '深圳', 'shenzhen');
INSERT INTO `spread_area` VALUES ('188', '20', '东莞', 'dongguan');
INSERT INTO `spread_area` VALUES ('189', '23', '成都', 'chengdu');
INSERT INTO `spread_area` VALUES ('190', '20', '佛山', 'foshan');
INSERT INTO `spread_area` VALUES ('191', '1', '朝阳', 'chaoyang');
INSERT INTO `spread_area` VALUES ('192', '1', '海淀', 'haidian');
INSERT INTO `spread_area` VALUES ('193', '11', '南京', 'nanjing');
INSERT INTO `spread_area` VALUES ('194', '3', '东丽', 'dongli');
INSERT INTO `spread_area` VALUES ('195', '12', '杭州', 'hangzhou');
INSERT INTO `spread_area` VALUES ('196', '18', '武汉', 'wuhan');
INSERT INTO `spread_area` VALUES ('197', '5', '石家庄', 'shijiazhuang');
INSERT INTO `spread_area` VALUES ('198', '8', '沈阳', 'shenyang');
INSERT INTO `spread_area` VALUES ('199', '27', '西安', 'xian');
INSERT INTO `spread_area` VALUES ('200', '1', '昌平', 'changping');
INSERT INTO `spread_area` VALUES ('201', '17', '郑州', 'zhengzhou');
INSERT INTO `spread_area` VALUES ('202', '25', '昆明', 'kunming');
INSERT INTO `spread_area` VALUES ('203', '9', '长春', 'changchun');
INSERT INTO `spread_area` VALUES ('204', '10', '哈尔滨', 'haerbin');
INSERT INTO `spread_area` VALUES ('205', '20', '中山', 'zhongshan');
INSERT INTO `spread_area` VALUES ('206', '16', '济南', 'jinan');
INSERT INTO `spread_area` VALUES ('207', '11', '苏州', 'suzhou');
INSERT INTO `spread_area` VALUES ('208', '8', '大连', 'dalian');
INSERT INTO `spread_area` VALUES ('209', '20', '江门', 'jiangmen');
INSERT INTO `spread_area` VALUES ('210', '19', '长沙', 'changsha');
INSERT INTO `spread_area` VALUES ('211', '16', '青岛', 'qingdao');
INSERT INTO `spread_area` VALUES ('212', '13', '蚌埠', 'bengbu');
INSERT INTO `spread_area` VALUES ('213', '14', '厦门', 'xiamen');
INSERT INTO `spread_area` VALUES ('214', '14', '福州', 'fuzhou');
INSERT INTO `spread_area` VALUES ('215', '6', '太原', 'taiyuan');
INSERT INTO `spread_area` VALUES ('216', '13', '合肥', 'hefei');
INSERT INTO `spread_area` VALUES ('217', '12', '温州', 'wenzhou');
INSERT INTO `spread_area` VALUES ('218', '16', '潍坊', 'weifang');
INSERT INTO `spread_area` VALUES ('219', '1', '西城', 'xicheng');
INSERT INTO `spread_area` VALUES ('220', '10', '大庆', 'daqing');
INSERT INTO `spread_area` VALUES ('221', '8', '鞍山', 'anshan');
INSERT INTO `spread_area` VALUES ('222', '7', '呼和浩特', 'huhehaote');
INSERT INTO `spread_area` VALUES ('223', '1', '大兴', 'daxing');
INSERT INTO `spread_area` VALUES ('224', '1', '通州', 'tongzhou');
INSERT INTO `spread_area` VALUES ('225', '14', '泉州', 'quanzhou');
INSERT INTO `spread_area` VALUES ('226', '16', '枣庄', 'zaozhuang');
INSERT INTO `spread_area` VALUES ('227', '21', '南宁', 'nanning');
INSERT INTO `spread_area` VALUES ('228', '11', '无锡', 'wuxi');
INSERT INTO `spread_area` VALUES ('229', '5', '唐山', 'tangshan');
INSERT INTO `spread_area` VALUES ('230', '11', '徐州', 'xuzhou');
INSERT INTO `spread_area` VALUES ('231', '7', '包头', 'baotou');
INSERT INTO `spread_area` VALUES ('232', '1', '东城', 'dongcheng');
INSERT INTO `spread_area` VALUES ('233', '4', '南岸', 'nanan2');
INSERT INTO `spread_area` VALUES ('234', '22', '海口', 'haikou');
INSERT INTO `spread_area` VALUES ('235', '11', '宿迁', 'suqian');
INSERT INTO `spread_area` VALUES ('236', '16', '临沂', 'linyi');
INSERT INTO `spread_area` VALUES ('237', '2', '闵行', 'minhang');
INSERT INTO `spread_area` VALUES ('238', '11', '南通', 'nantong');
INSERT INTO `spread_area` VALUES ('240', '24', '贵阳', 'guiyang');
INSERT INTO `spread_area` VALUES ('241', '3', '河东', 'hedong');
INSERT INTO `spread_area` VALUES ('242', '2', '浦东', 'pudong');
INSERT INTO `spread_area` VALUES ('244', '16', '淄博', 'zibo');
INSERT INTO `spread_area` VALUES ('245', '16', '济宁', 'jining');
INSERT INTO `spread_area` VALUES ('246', '11', '常州', 'changzhou');
INSERT INTO `spread_area` VALUES ('247', '11', '淮安', 'huaian');
INSERT INTO `spread_area` VALUES ('248', '1', '宣武', 'xuanwu');
INSERT INTO `spread_area` VALUES ('249', '1', '石景山', 'shijingshan');
INSERT INTO `spread_area` VALUES ('250', '5', '保定', 'baoding');
INSERT INTO `spread_area` VALUES ('251', '4', '江北', 'jiangbei');
INSERT INTO `spread_area` VALUES ('252', '16', '聊城', 'liaocheng');
INSERT INTO `spread_area` VALUES ('253', '28', '兰州', 'lanzhou');
INSERT INTO `spread_area` VALUES ('254', '5', '邯郸', 'handan');
INSERT INTO `spread_area` VALUES ('255', '5', '沧州', 'cangzhou');
INSERT INTO `spread_area` VALUES ('256', '12', '金华', 'jinhua');
INSERT INTO `spread_area` VALUES ('257', '11', '盐城', 'yancheng');
INSERT INTO `spread_area` VALUES ('258', '19', '衡阳', 'hengyang');
INSERT INTO `spread_area` VALUES ('259', '11', '泰州', 'taizhou');
INSERT INTO `spread_area` VALUES ('261', '4', '九龙坡', 'jiulongpo');
INSERT INTO `spread_area` VALUES ('262', '9', '吉林', 'jilin2');
INSERT INTO `spread_area` VALUES ('263', '17', '新乡', 'xinxiang');
INSERT INTO `spread_area` VALUES ('264', '5', '廊坊', 'langfang');
INSERT INTO `spread_area` VALUES ('265', '8', '抚顺', 'fushun');
INSERT INTO `spread_area` VALUES ('266', '23', '绵阳', 'mianyang');
INSERT INTO `spread_area` VALUES ('267', '11', '连云港', 'lianyungang');
INSERT INTO `spread_area` VALUES ('268', '17', '焦作', 'jiaozuo');
INSERT INTO `spread_area` VALUES ('269', '5', '邢台', 'xingtai');
INSERT INTO `spread_area` VALUES ('270', '3', '塘沽', 'tanggu');
INSERT INTO `spread_area` VALUES ('271', '8', '盘锦', 'panjin');
INSERT INTO `spread_area` VALUES ('272', '17', '南阳', 'nanyang');
INSERT INTO `spread_area` VALUES ('273', '8', '葫芦岛', 'huludao');
INSERT INTO `spread_area` VALUES ('274', '20', '阳江', 'yangjiang');
INSERT INTO `spread_area` VALUES ('275', '8', '丹东', 'dandong');
INSERT INTO `spread_area` VALUES ('276', '16', '泰安', 'taian');
INSERT INTO `spread_area` VALUES ('277', '17', '许昌', 'xuchang');
INSERT INTO `spread_area` VALUES ('278', '16', '东营', 'dongying');
INSERT INTO `spread_area` VALUES ('279', '17', '洛阳', 'luoyang');
INSERT INTO `spread_area` VALUES ('281', '14', '莆田', 'putian');
INSERT INTO `spread_area` VALUES ('282', '3', '南开', 'nankai');
INSERT INTO `spread_area` VALUES ('283', '16', '威海', 'weihai');
INSERT INTO `spread_area` VALUES ('284', '20', '珠海', 'zhuhai');
INSERT INTO `spread_area` VALUES ('285', '18', '襄阳', 'xiangyang');
INSERT INTO `spread_area` VALUES ('286', '5', '衡水', 'hengshui');
INSERT INTO `spread_area` VALUES ('287', '12', '嘉兴', 'jiaxing');
INSERT INTO `spread_area` VALUES ('288', '17', '濮阳', 'puyang');
INSERT INTO `spread_area` VALUES ('289', '23', '德阳', 'deyang');
INSERT INTO `spread_area` VALUES ('290', '16', '滨州', 'binzhou');
INSERT INTO `spread_area` VALUES ('291', '5', '秦皇岛', 'qinhuangdao');
INSERT INTO `spread_area` VALUES ('292', '4', '渝中', 'yuzhong');
INSERT INTO `spread_area` VALUES ('293', '1', '崇文', 'chongwen');
INSERT INTO `spread_area` VALUES ('294', '1', '顺义', 'shunyi');
INSERT INTO `spread_area` VALUES ('295', '12', '绍兴', 'shaoxing');
INSERT INTO `spread_area` VALUES ('296', '18', '荆州', 'jingzhou');
INSERT INTO `spread_area` VALUES ('297', '15', '南昌', 'nanchang');
INSERT INTO `spread_area` VALUES ('298', '16', '德州', 'dezhou');
INSERT INTO `spread_area` VALUES ('299', '6', '临汾', 'linfen');
INSERT INTO `spread_area` VALUES ('300', '17', '周口', 'zhoukou');
INSERT INTO `spread_area` VALUES ('301', '11', '扬州', 'yangzhou');
INSERT INTO `spread_area` VALUES ('302', '20', '惠州', 'huizhou');
INSERT INTO `spread_area` VALUES ('303', '10', '佳木斯', 'jiamusi');
INSERT INTO `spread_area` VALUES ('304', '20', '揭阳', 'jieyang');
INSERT INTO `spread_area` VALUES ('305', '29', '银川', 'yinchuan');
INSERT INTO `spread_area` VALUES ('306', '17', '开封', 'kaifeng');
INSERT INTO `spread_area` VALUES ('307', '1', '房山', 'fangshan');
INSERT INTO `spread_area` VALUES ('308', '8', '营口', 'yingkou');
INSERT INTO `spread_area` VALUES ('309', '11', '镇江', 'zhenjiang');
INSERT INTO `spread_area` VALUES ('310', '3', '河西', 'hexi');
INSERT INTO `spread_area` VALUES ('311', '16', '菏泽', 'heze');
INSERT INTO `spread_area` VALUES ('312', '7', '鄂尔多斯', 'eerduosi');
INSERT INTO `spread_area` VALUES ('313', '16', '日照', 'rizhao');
INSERT INTO `spread_area` VALUES ('314', '2', '徐汇', 'xuhui');
INSERT INTO `spread_area` VALUES ('315', '19', '永州', 'yongzhou');
INSERT INTO `spread_area` VALUES ('316', '15', '上饶', 'shangrao');
INSERT INTO `spread_area` VALUES ('317', '20', '汕头', 'shantou');
INSERT INTO `spread_area` VALUES ('318', '25', '曲靖', 'qujing');
INSERT INTO `spread_area` VALUES ('319', '21', '桂林', 'guilin');
INSERT INTO `spread_area` VALUES ('320', '17', '商丘', 'shangqiu');
INSERT INTO `spread_area` VALUES ('321', '18', '宜昌', 'yichang');
INSERT INTO `spread_area` VALUES ('322', '7', '赤峰', 'chifeng');
INSERT INTO `spread_area` VALUES ('323', '13', '芜湖', 'wuhu');
INSERT INTO `spread_area` VALUES ('324', '7', '巴彦淖尔盟', 'bayannaoermeng');
INSERT INTO `spread_area` VALUES ('325', '17', '安阳', 'anyang');
INSERT INTO `spread_area` VALUES ('326', '3', '北辰', 'beichen');
INSERT INTO `spread_area` VALUES ('327', '17', '平顶山', 'pingdingshan');
INSERT INTO `spread_area` VALUES ('328', '4', '沙坪坝', 'shapingba');
INSERT INTO `spread_area` VALUES ('329', '19', '常德', 'changde');
INSERT INTO `spread_area` VALUES ('330', '19', '湘潭', 'xiangtan');
INSERT INTO `spread_area` VALUES ('331', '2', '松江', 'songjiang');
INSERT INTO `spread_area` VALUES ('332', '27', '咸阳', 'xianyang');
INSERT INTO `spread_area` VALUES ('333', '13', '淮南', 'huainan');
INSERT INTO `spread_area` VALUES ('334', '8', '辽阳', 'liaoyang');
INSERT INTO `spread_area` VALUES ('335', '10', '齐齐哈尔', 'qiqihaer');
INSERT INTO `spread_area` VALUES ('336', '15', '九江', 'jiujiang');
INSERT INTO `spread_area` VALUES ('337', '2', '长宁', 'changning');
INSERT INTO `spread_area` VALUES ('338', '3', '西青', 'xiqing');
INSERT INTO `spread_area` VALUES ('339', '8', '锦州', 'jinzhou');
INSERT INTO `spread_area` VALUES ('340', '2', '嘉定', 'jiading');
INSERT INTO `spread_area` VALUES ('341', '19', '岳阳', 'yueyang');
INSERT INTO `spread_area` VALUES ('342', '19', '株洲', 'zhuzhou');
INSERT INTO `spread_area` VALUES ('343', '5', '张家口', 'zhangjiakou');
INSERT INTO `spread_area` VALUES ('344', '10', '牡丹江', 'mudanjiang');
INSERT INTO `spread_area` VALUES ('345', '4', '万州', 'wanzhou');
INSERT INTO `spread_area` VALUES ('346', '14', '龙岩', 'longyan');
INSERT INTO `spread_area` VALUES ('347', '12', '湖州', 'huzhou');
INSERT INTO `spread_area` VALUES ('348', '19', '邵阳', 'shaoyang');
INSERT INTO `spread_area` VALUES ('349', '16', '莱芜', 'laiwu');
INSERT INTO `spread_area` VALUES ('350', '2', '宝山', 'baoshan2');
INSERT INTO `spread_area` VALUES ('351', '27', '渭南', 'weinan');
INSERT INTO `spread_area` VALUES ('352', '21', '柳州', 'liuzhou');
INSERT INTO `spread_area` VALUES ('353', '6', '运城', 'yuncheng');
INSERT INTO `spread_area` VALUES ('354', '13', '滁州', 'chuzhou');
INSERT INTO `spread_area` VALUES ('355', '13', '阜阳', 'fuyang');
INSERT INTO `spread_area` VALUES ('356', '2', '虹口', 'hongkou');
INSERT INTO `spread_area` VALUES ('357', '6', '大同', 'datong');
INSERT INTO `spread_area` VALUES ('358', '2', '杨浦', 'yangpu');
INSERT INTO `spread_area` VALUES ('359', '14', '漳州', 'zhangzhou');
INSERT INTO `spread_area` VALUES ('360', '6', '晋中', 'jinzhong');
INSERT INTO `spread_area` VALUES ('361', '22', '三亚', 'sanya');
INSERT INTO `spread_area` VALUES ('362', '9', '四平', 'siping');
INSERT INTO `spread_area` VALUES ('363', '17', '信阳', 'xinyang');
INSERT INTO `spread_area` VALUES ('364', '12', '丽水', 'lishui');
INSERT INTO `spread_area` VALUES ('365', '13', '巢湖', 'chaohu');
INSERT INTO `spread_area` VALUES ('366', '13', '宿州', 'suzhou2');
INSERT INTO `spread_area` VALUES ('367', '6', '长治', 'changzhi');
INSERT INTO `spread_area` VALUES ('368', '10', '绥化', 'suihua');
INSERT INTO `spread_area` VALUES ('369', '15', '萍乡', 'pingxiang');
INSERT INTO `spread_area` VALUES ('370', '3', '河北', 'hebei2');
INSERT INTO `spread_area` VALUES ('371', '20', '肇庆', 'zhaoqing');
INSERT INTO `spread_area` VALUES ('372', '20', '茂名', 'maoming');
INSERT INTO `spread_area` VALUES ('373', '21', '玉林', 'yulin');
INSERT INTO `spread_area` VALUES ('374', '13', '铜陵', 'tongling');
INSERT INTO `spread_area` VALUES ('375', '27', '宝鸡', 'baoji');
INSERT INTO `spread_area` VALUES ('377', '15', '宜春', 'yichun');
INSERT INTO `spread_area` VALUES ('378', '30', '西宁', 'xining');
INSERT INTO `spread_area` VALUES ('379', '31', '乌鲁木齐', 'wulumuqi');
INSERT INTO `spread_area` VALUES ('380', '27', '榆林', 'yulin2');
INSERT INTO `spread_area` VALUES ('381', '18', '十堰', 'shiyan');
INSERT INTO `spread_area` VALUES ('382', '13', '黄山', 'huangshan');
INSERT INTO `spread_area` VALUES ('383', '18', '荆门', 'jingmen');
INSERT INTO `spread_area` VALUES ('384', '13', '六安', 'luan');
INSERT INTO `spread_area` VALUES ('385', '20', '清远', 'qingyuan');
INSERT INTO `spread_area` VALUES ('386', '18', '黄冈', 'huanggang');
INSERT INTO `spread_area` VALUES ('387', '19', '娄底', 'loudi');
INSERT INTO `spread_area` VALUES ('388', '15', '赣州', 'ganzhou');
INSERT INTO `spread_area` VALUES ('389', '23', '南充', 'nanchong');
INSERT INTO `spread_area` VALUES ('390', '20', '广州', 'guangzhou');
INSERT INTO `spread_area` VALUES ('391', '16', '烟台', 'yantai');
INSERT INTO `spread_area` VALUES ('392', '2', '闸北', 'zhabei');
INSERT INTO `spread_area` VALUES ('394', '14', '宁德', 'ningde');
INSERT INTO `spread_area` VALUES ('398', '1', '门头沟', 'mentougou');
INSERT INTO `spread_area` VALUES ('399', '1', '平谷', 'pinggu');
INSERT INTO `spread_area` VALUES ('400', '1', '怀柔', 'huairou');
INSERT INTO `spread_area` VALUES ('401', '1', '密云', 'miyun');
INSERT INTO `spread_area` VALUES ('402', '1', '延庆', 'yanqing');
INSERT INTO `spread_area` VALUES ('403', '2', '黄埔', 'huangpu');
INSERT INTO `spread_area` VALUES ('405', '2', '卢湾', 'luwan');
INSERT INTO `spread_area` VALUES ('406', '2', '静安', 'jingan');
INSERT INTO `spread_area` VALUES ('407', '2', '金山', 'jinshan');
INSERT INTO `spread_area` VALUES ('408', '2', '青浦', 'qingpu');
INSERT INTO `spread_area` VALUES ('409', '2', '南汇', 'nanhui');
INSERT INTO `spread_area` VALUES ('410', '2', '奉贤', 'fengxian');
INSERT INTO `spread_area` VALUES ('411', '2', '崇明', 'chongming');
INSERT INTO `spread_area` VALUES ('412', '3', '和平', 'heping');
INSERT INTO `spread_area` VALUES ('413', '3', '津南', 'jinnan');
INSERT INTO `spread_area` VALUES ('414', '3', '武清', 'wuqing');
INSERT INTO `spread_area` VALUES ('415', '3', '红桥', 'hongqiao');
INSERT INTO `spread_area` VALUES ('416', '3', '汉沽', 'hangu');
INSERT INTO `spread_area` VALUES ('417', '3', '大港', 'dagang');
INSERT INTO `spread_area` VALUES ('418', '3', '宁河', 'ninghe');
INSERT INTO `spread_area` VALUES ('419', '3', '静海', 'jinghai');
INSERT INTO `spread_area` VALUES ('420', '3', '宝坻', 'baodi');
INSERT INTO `spread_area` VALUES ('421', '3', '蓟县', 'jixian');
INSERT INTO `spread_area` VALUES ('422', '4', '涪陵', 'fuling');
INSERT INTO `spread_area` VALUES ('424', '4', '大渡口', 'dadukou');
INSERT INTO `spread_area` VALUES ('425', '4', '北碚', 'beibei');
INSERT INTO `spread_area` VALUES ('426', '4', '万盛', 'wansheng');
INSERT INTO `spread_area` VALUES ('427', '4', '双桥', 'shuangqiao');
INSERT INTO `spread_area` VALUES ('428', '4', '渝北', 'yubei');
INSERT INTO `spread_area` VALUES ('429', '4', '巴南', 'banan');
INSERT INTO `spread_area` VALUES ('430', '4', '黔江', 'qianjiang2');
INSERT INTO `spread_area` VALUES ('431', '4', '长寿', 'changshou');
INSERT INTO `spread_area` VALUES ('432', '4', '綦江', 'qijiang');
INSERT INTO `spread_area` VALUES ('433', '4', '潼南', 'tongnan');
INSERT INTO `spread_area` VALUES ('434', '4', '铜梁', 'tongliang');
INSERT INTO `spread_area` VALUES ('435', '4', '大足', 'dazu');
INSERT INTO `spread_area` VALUES ('436', '4', '荣昌', 'rongchang');
INSERT INTO `spread_area` VALUES ('437', '4', '壁山', 'bishan');
INSERT INTO `spread_area` VALUES ('438', '4', '梁平', 'liangping');
INSERT INTO `spread_area` VALUES ('439', '4', '城口', 'chengkou');
INSERT INTO `spread_area` VALUES ('440', '4', '丰都', 'fengdu');
INSERT INTO `spread_area` VALUES ('441', '4', '垫江', 'dianjiang');
INSERT INTO `spread_area` VALUES ('442', '4', '武隆', 'wulong');
INSERT INTO `spread_area` VALUES ('443', '4', '忠县', 'zhongxian');
INSERT INTO `spread_area` VALUES ('444', '4', '开县', 'kaixian');
INSERT INTO `spread_area` VALUES ('445', '4', '云阳', 'yunyang');
INSERT INTO `spread_area` VALUES ('446', '4', '奉节', 'fengjie');
INSERT INTO `spread_area` VALUES ('447', '4', '巫山', 'wushan');
INSERT INTO `spread_area` VALUES ('448', '4', '巫溪', 'wuxi2');
INSERT INTO `spread_area` VALUES ('449', '4', '石柱', 'shizhu');
INSERT INTO `spread_area` VALUES ('450', '4', '秀山', 'xiushan');
INSERT INTO `spread_area` VALUES ('451', '4', '酉阳', 'youyang');
INSERT INTO `spread_area` VALUES ('452', '4', '彭水', 'pengshui');
INSERT INTO `spread_area` VALUES ('453', '4', '江津', 'jiangjin');
INSERT INTO `spread_area` VALUES ('454', '4', '合川', 'hechuan');
INSERT INTO `spread_area` VALUES ('455', '4', '永川', 'yongchuan');
INSERT INTO `spread_area` VALUES ('456', '4', '南川', 'nanchuan');
INSERT INTO `spread_area` VALUES ('457', '5', '承德', 'chengde');
INSERT INTO `spread_area` VALUES ('458', '5', '任丘', 'renqiu');
INSERT INTO `spread_area` VALUES ('459', '5', '迁安', 'qianan');
INSERT INTO `spread_area` VALUES ('460', '5', '辛集', 'xinji');
INSERT INTO `spread_area` VALUES ('461', '5', '玉田', 'yutian');
INSERT INTO `spread_area` VALUES ('462', '5', '永清', 'yongqing');
INSERT INTO `spread_area` VALUES ('463', '5', '涿州', 'zhuozhou');
INSERT INTO `spread_area` VALUES ('464', '5', '遵化', 'zunhua');
INSERT INTO `spread_area` VALUES ('465', '5', '大厂', 'dachang');
INSERT INTO `spread_area` VALUES ('466', '5', '乐亭', 'leting');
INSERT INTO `spread_area` VALUES ('467', '5', '兴隆', 'xinglong');
INSERT INTO `spread_area` VALUES ('468', '6', '阳泉', 'yangquan');
INSERT INTO `spread_area` VALUES ('469', '6', '晋城', 'jincheng');
INSERT INTO `spread_area` VALUES ('470', '6', '朔州', 'shuozhou');
INSERT INTO `spread_area` VALUES ('471', '6', '吕梁', 'lvliang');
INSERT INTO `spread_area` VALUES ('472', '6', '忻州', 'xinzhou');
INSERT INTO `spread_area` VALUES ('480', '6', '榆次', 'yuci');
INSERT INTO `spread_area` VALUES ('481', '6', '孝义', 'xiaoyi');
INSERT INTO `spread_area` VALUES ('482', '6', '介休', 'jiexiu');
INSERT INTO `spread_area` VALUES ('483', '6', '离石', 'lishi');
INSERT INTO `spread_area` VALUES ('484', '6', '河津', 'hejin');
INSERT INTO `spread_area` VALUES ('485', '6', '汾阳', 'fenyang');
INSERT INTO `spread_area` VALUES ('486', '6', '侯马', 'houma');
INSERT INTO `spread_area` VALUES ('487', '7', '乌海', 'wuhai');
INSERT INTO `spread_area` VALUES ('488', '7', '呼伦贝尔盟', 'hulunbeiermeng');
INSERT INTO `spread_area` VALUES ('489', '7', '阿拉善盟', 'alashanmeng');
INSERT INTO `spread_area` VALUES ('490', '7', '哲里木盟', 'zhelimumeng');
INSERT INTO `spread_area` VALUES ('491', '7', '兴安盟', 'xinganmeng');
INSERT INTO `spread_area` VALUES ('492', '7', '乌兰察布盟', 'wulanchabumeng');
INSERT INTO `spread_area` VALUES ('493', '7', '锡林郭勒盟', 'xilinguolemeng');
INSERT INTO `spread_area` VALUES ('494', '7', '通辽', 'tongliao');
INSERT INTO `spread_area` VALUES ('495', '7', '海拉尔', 'hailaer');
INSERT INTO `spread_area` VALUES ('496', '7', '临河', 'linhe');
INSERT INTO `spread_area` VALUES ('497', '7', '呼市', 'hushi');
INSERT INTO `spread_area` VALUES ('498', '7', '集宁', 'jining2');
INSERT INTO `spread_area` VALUES ('499', '7', '牙克石', 'yakeshi');
INSERT INTO `spread_area` VALUES ('500', '7', '乌兰浩特', 'wulanhaote');
INSERT INTO `spread_area` VALUES ('501', '7', '锡林浩特', 'xilinhaote');
INSERT INTO `spread_area` VALUES ('502', '8', '本溪', 'benxi');
INSERT INTO `spread_area` VALUES ('503', '8', '阜新', 'fuxin');
INSERT INTO `spread_area` VALUES ('504', '8', '铁岭', 'tieling');
INSERT INTO `spread_area` VALUES ('505', '8', '海城', 'haicheng');
INSERT INTO `spread_area` VALUES ('506', '8', '大石桥', 'dashiqiao');
INSERT INTO `spread_area` VALUES ('507', '8', '辽河', 'liaohe');
INSERT INTO `spread_area` VALUES ('508', '8', '瓦房店', 'wafangdian');
INSERT INTO `spread_area` VALUES ('509', '9', '辽源', 'liaoyuan');
INSERT INTO `spread_area` VALUES ('510', '9', '通化', 'tonghua');
INSERT INTO `spread_area` VALUES ('511', '9', '白山', 'baishan');
INSERT INTO `spread_area` VALUES ('512', '9', '松原', 'songyuan');
INSERT INTO `spread_area` VALUES ('513', '9', '白城', 'baicheng');
INSERT INTO `spread_area` VALUES ('514', '9', '延吉', 'yanji');
INSERT INTO `spread_area` VALUES ('515', '9', '长岭', 'changling');
INSERT INTO `spread_area` VALUES ('516', '9', '梅河口', 'meihekou');
INSERT INTO `spread_area` VALUES ('517', '9', '靖宇', 'jingyu');
INSERT INTO `spread_area` VALUES ('518', '9', '双辽', 'shuangliao');
INSERT INTO `spread_area` VALUES ('519', '9', '扶余', 'fuyu');
INSERT INTO `spread_area` VALUES ('520', '9', '顺达', 'shunda');
INSERT INTO `spread_area` VALUES ('521', '10', '鹤岗', 'hegang');
INSERT INTO `spread_area` VALUES ('522', '10', '鸡西', 'jixi');
INSERT INTO `spread_area` VALUES ('523', '10', '黑河', 'heihe');
INSERT INTO `spread_area` VALUES ('524', '10', '双鸭山', 'shuangyashan');
INSERT INTO `spread_area` VALUES ('525', '10', '伊春', 'yichun2');
INSERT INTO `spread_area` VALUES ('526', '10', '七台河', 'qitaihe');
INSERT INTO `spread_area` VALUES ('527', '10', '大兴安岭', 'daxinganling');
INSERT INTO `spread_area` VALUES ('528', '10', '北安', 'beian');
INSERT INTO `spread_area` VALUES ('529', '10', '齐市', 'qishi');
INSERT INTO `spread_area` VALUES ('530', '10', '铁力', 'tieli');
INSERT INTO `spread_area` VALUES ('531', '10', '嫩江', 'nenjiang');
INSERT INTO `spread_area` VALUES ('532', '10', '南岗', 'nangang');
INSERT INTO `spread_area` VALUES ('533', '10', '尚志', 'shangzhi');
INSERT INTO `spread_area` VALUES ('534', '10', '绥芬河', 'suifenhe');
INSERT INTO `spread_area` VALUES ('535', '10', '加格达奇', 'jiagedaqi');
INSERT INTO `spread_area` VALUES ('536', '11', '常熟', 'changshu');
INSERT INTO `spread_area` VALUES ('537', '11', '丹阳', 'danyang');
INSERT INTO `spread_area` VALUES ('538', '11', '江阴', 'jiangyin');
INSERT INTO `spread_area` VALUES ('539', '11', '昆山', 'kunshan');
INSERT INTO `spread_area` VALUES ('540', '11', '张家港', 'zhangjiagang');
INSERT INTO `spread_area` VALUES ('541', '11', '泰兴', 'taixing');
INSERT INTO `spread_area` VALUES ('542', '11', '吴江', 'wujiang');
INSERT INTO `spread_area` VALUES ('543', '11', '太仓', 'taicang');
INSERT INTO `spread_area` VALUES ('544', '11', '仪征', 'yizheng');
INSERT INTO `spread_area` VALUES ('545', '11', '宜兴', 'yixing');
INSERT INTO `spread_area` VALUES ('546', '11', '海安', 'haian');
INSERT INTO `spread_area` VALUES ('547', '11', '靖江', 'jingjiang');
INSERT INTO `spread_area` VALUES ('548', '11', '江宁', 'jiangning');
INSERT INTO `spread_area` VALUES ('549', '11', '江都', 'jiangdu');
INSERT INTO `spread_area` VALUES ('550', '11', '淮阴', 'huaiyin');
INSERT INTO `spread_area` VALUES ('571', '32', '拉萨', 'lasa');
INSERT INTO `spread_area` VALUES ('572', '32', '日喀则', 'rikaze');
INSERT INTO `spread_area` VALUES ('573', '32', '山南', 'shannan');
INSERT INTO `spread_area` VALUES ('574', '32', '林芝', 'linzhi');
INSERT INTO `spread_area` VALUES ('575', '32', '昌都', 'changdu');
INSERT INTO `spread_area` VALUES ('576', '32', '阿里', 'ali');
INSERT INTO `spread_area` VALUES ('577', '32', '那曲', 'naqu');
INSERT INTO `spread_area` VALUES ('583', '12', '衢州', 'quzhou');
INSERT INTO `spread_area` VALUES ('584', '12', '舟山', 'zhoushan');
INSERT INTO `spread_area` VALUES ('585', '12', '黄岩', 'huangyan');
INSERT INTO `spread_area` VALUES ('586', '12', '乐清', 'yueqing');
INSERT INTO `spread_area` VALUES ('587', '12', '东阳', 'dongyang');
INSERT INTO `spread_area` VALUES ('588', '12', '瑞安', 'ruian');
INSERT INTO `spread_area` VALUES ('589', '12', '平阳', 'pingyang');
INSERT INTO `spread_area` VALUES ('590', '12', '萧山', 'xiaoshan');
INSERT INTO `spread_area` VALUES ('591', '12', '永康', 'yongkang');
INSERT INTO `spread_area` VALUES ('592', '12', '义乌', 'yiwu');
INSERT INTO `spread_area` VALUES ('593', '12', '长兴', 'changxing');
INSERT INTO `spread_area` VALUES ('594', '12', '诸暨', 'zhuji');
INSERT INTO `spread_area` VALUES ('595', '12', '玉环', 'yuhuan');
INSERT INTO `spread_area` VALUES ('596', '12', '余杭', 'yuhang');
INSERT INTO `spread_area` VALUES ('597', '12', '余姚', 'yuyao');
INSERT INTO `spread_area` VALUES ('598', '12', '永嘉', 'yongjia');
INSERT INTO `spread_area` VALUES ('599', '12', '嵊州', 'shengzhou');
INSERT INTO `spread_area` VALUES ('600', '12', '上虞', 'shangyu');
INSERT INTO `spread_area` VALUES ('601', '12', '温岭', 'wenling');
INSERT INTO `spread_area` VALUES ('602', '12', '桐庐', 'tonglu');
INSERT INTO `spread_area` VALUES ('603', '12', '天台', 'tiantai');
INSERT INTO `spread_area` VALUES ('604', '12', '建德', 'jiande');
INSERT INTO `spread_area` VALUES ('605', '12', '浒山', 'hushan');
INSERT INTO `spread_area` VALUES ('606', '12', '康桥', 'kangqiao');
INSERT INTO `spread_area` VALUES ('607', '12', '临安', 'linan');
INSERT INTO `spread_area` VALUES ('608', '12', '龙游', 'longyou');
INSERT INTO `spread_area` VALUES ('609', '12', '临海', 'linhai');
INSERT INTO `spread_area` VALUES ('610', '12', '德清', 'deqing');
INSERT INTO `spread_area` VALUES ('611', '12', '富阳', 'fuyang2');
INSERT INTO `spread_area` VALUES ('612', '12', '苍南', 'cangnan');
INSERT INTO `spread_area` VALUES ('613', '12', '安吉', 'anji');
INSERT INTO `spread_area` VALUES ('614', '12', '慈溪', 'cixi');
INSERT INTO `spread_area` VALUES ('615', '13', '马鞍山', 'maanshan');
INSERT INTO `spread_area` VALUES ('616', '13', '淮北', 'huaibei');
INSERT INTO `spread_area` VALUES ('617', '13', '安庆', 'anqing');
INSERT INTO `spread_area` VALUES ('618', '13', '池州', 'chizhou');
INSERT INTO `spread_area` VALUES ('619', '13', '宣城', 'xuancheng');
INSERT INTO `spread_area` VALUES ('620', '13', '亳州', 'bozhou');
INSERT INTO `spread_area` VALUES ('621', '14', '三明', 'sanming');
INSERT INTO `spread_area` VALUES ('622', '14', '南平', 'nanping');
INSERT INTO `spread_area` VALUES ('623', '14', '晋江', 'jinjiang');
INSERT INTO `spread_area` VALUES ('624', '14', '邵武', 'shaowu');
INSERT INTO `spread_area` VALUES ('625', '14', '武夷山', 'wuyishan');
INSERT INTO `spread_area` VALUES ('626', '14', '沙县', 'shaxian');
INSERT INTO `spread_area` VALUES ('627', '14', '永安', 'yongan');
INSERT INTO `spread_area` VALUES ('628', '14', '建瓯', 'jianou');
INSERT INTO `spread_area` VALUES ('629', '14', '南安', 'nanan');
INSERT INTO `spread_area` VALUES ('630', '14', '浦城', 'pucheng');
INSERT INTO `spread_area` VALUES ('631', '14', '福清', 'fuqing');
INSERT INTO `spread_area` VALUES ('632', '15', '景德镇', 'jingdezhen');
INSERT INTO `spread_area` VALUES ('633', '15', '鹰潭', 'yingtan');
INSERT INTO `spread_area` VALUES ('635', '15', '新馀', 'xinyu');
INSERT INTO `spread_area` VALUES ('636', '15', '吉安', 'jian');
INSERT INTO `spread_area` VALUES ('637', '15', '抚州', 'fuzhou2');
INSERT INTO `spread_area` VALUES ('638', '15', '赣南', 'gannan');
INSERT INTO `spread_area` VALUES ('639', '16', '招远', 'zhaoyuan');
INSERT INTO `spread_area` VALUES ('640', '16', '高密', 'gaomi');
INSERT INTO `spread_area` VALUES ('641', '16', '龙口', 'longkou');
INSERT INTO `spread_area` VALUES ('642', '16', '蔡州', 'caizhou');
INSERT INTO `spread_area` VALUES ('643', '16', '青州', 'qingzhou');
INSERT INTO `spread_area` VALUES ('644', '15', '荣城', 'rongcheng');
INSERT INTO `spread_area` VALUES ('645', '16', '寿光', 'shouguang');
INSERT INTO `spread_area` VALUES ('646', '16', '文登', 'wendeng');
INSERT INTO `spread_area` VALUES ('647', '16', '滕州', 'tengzhou');
INSERT INTO `spread_area` VALUES ('648', '16', '沂水', 'yishui');
INSERT INTO `spread_area` VALUES ('649', '16', '平度', 'pingdu');
INSERT INTO `spread_area` VALUES ('650', '16', '即墨', 'jimo');
INSERT INTO `spread_area` VALUES ('651', '16', '胶南', 'jiaonan');
INSERT INTO `spread_area` VALUES ('652', '16', '莱西', 'laixi');
INSERT INTO `spread_area` VALUES ('653', '16', '莱阳', 'laiyang');
INSERT INTO `spread_area` VALUES ('654', '17', '鹤壁', 'hebi');
INSERT INTO `spread_area` VALUES ('655', '17', '漯河', 'luohe');
INSERT INTO `spread_area` VALUES ('656', '17', '三门峡', 'sanmenxia');
INSERT INTO `spread_area` VALUES ('657', '17', '驻马店', 'zhumadian');
INSERT INTO `spread_area` VALUES ('658', '17', '济源', 'jiyuan');
INSERT INTO `spread_area` VALUES ('659', '17', '林州', 'linzhou');
INSERT INTO `spread_area` VALUES ('660', '17', '新郑', 'xinzheng');
INSERT INTO `spread_area` VALUES ('661', '18', '黄石', 'huangshi');
INSERT INTO `spread_area` VALUES ('662', '18', '恩施', 'enshi');
INSERT INTO `spread_area` VALUES ('663', '18', '潜江', 'qianjiang');
INSERT INTO `spread_area` VALUES ('664', '18', '天门', 'tianmen');
INSERT INTO `spread_area` VALUES ('665', '18', '仙桃', 'xiantao');
INSERT INTO `spread_area` VALUES ('666', '18', '随州', 'suizhou');
INSERT INTO `spread_area` VALUES ('667', '18', '咸宁', 'xianning');
INSERT INTO `spread_area` VALUES ('668', '18', '孝感', 'xiaogan');
INSERT INTO `spread_area` VALUES ('669', '18', '鄂州', 'ezhou');
INSERT INTO `spread_area` VALUES ('671', '18', '利川', 'lichuan');
INSERT INTO `spread_area` VALUES ('672', '19', '益阳', 'yiyang');
INSERT INTO `spread_area` VALUES ('673', '19', '怀化', 'huaihua');
INSERT INTO `spread_area` VALUES ('674', '19', '郴州', 'chenzhou');
INSERT INTO `spread_area` VALUES ('675', '19', '湘西', 'xiangxi');
INSERT INTO `spread_area` VALUES ('676', '19', '张家界', 'zhangjiajie');
INSERT INTO `spread_area` VALUES ('677', '19', '马王堆', 'mawangdui');
INSERT INTO `spread_area` VALUES ('678', '19', '吉首', 'jishou');
INSERT INTO `spread_area` VALUES ('679', '19', '浏阳', 'liuyang');
INSERT INTO `spread_area` VALUES ('680', '19', '邵东', 'shaodong');
INSERT INTO `spread_area` VALUES ('681', '20', '韶关', 'shaoguan');
INSERT INTO `spread_area` VALUES ('682', '20', '湛江', 'zhanjiang');
INSERT INTO `spread_area` VALUES ('683', '20', '梅州', 'meizhou');
INSERT INTO `spread_area` VALUES ('684', '20', '汕尾', 'shanwei');
INSERT INTO `spread_area` VALUES ('685', '20', '河源', 'heyuan');
INSERT INTO `spread_area` VALUES ('686', '20', '潮州', 'chaozhou');
INSERT INTO `spread_area` VALUES ('687', '20', '云浮', 'yunfu');
INSERT INTO `spread_area` VALUES ('688', '20', '端州', 'duanzhou');
INSERT INTO `spread_area` VALUES ('689', '20', '开平', 'kaiping');
INSERT INTO `spread_area` VALUES ('691', '20', '台山', 'taishan');
INSERT INTO `spread_area` VALUES ('692', '20', '普宁', 'puning');
INSERT INTO `spread_area` VALUES ('694', '20', '粤东', 'yuedong');
INSERT INTO `spread_area` VALUES ('695', '20', '英德', 'yingde');
INSERT INTO `spread_area` VALUES ('696', '20', '新会', 'xinhui');
INSERT INTO `spread_area` VALUES ('697', '20', '阳春', 'yangchun');
INSERT INTO `spread_area` VALUES ('698', '20', '揭西', 'jiexi');
INSERT INTO `spread_area` VALUES ('699', '20', '流沙', 'liusha');
INSERT INTO `spread_area` VALUES ('700', '20', '鹤山', 'heshan');
INSERT INTO `spread_area` VALUES ('701', '20', '高要', 'gaoyao');
INSERT INTO `spread_area` VALUES ('702', '20', '恩平', 'enping');
INSERT INTO `spread_area` VALUES ('704', '20', '澄海', 'chenghai');
INSERT INTO `spread_area` VALUES ('705', '20', '揭东', 'jiedong');
INSERT INTO `spread_area` VALUES ('706', '21', '梧州', 'wuzhou');
INSERT INTO `spread_area` VALUES ('707', '21', '北海', 'beihai');
INSERT INTO `spread_area` VALUES ('708', '21', '防城港', 'fangchenggang');
INSERT INTO `spread_area` VALUES ('709', '21', '钦州', 'qinzhou');
INSERT INTO `spread_area` VALUES ('710', '21', '贵港', 'guigang');
INSERT INTO `spread_area` VALUES ('711', '21', '南宁地区', 'nanningdiqu');
INSERT INTO `spread_area` VALUES ('712', '21', '柳州地区', 'liuzhoudiqu');
INSERT INTO `spread_area` VALUES ('713', '21', '贺州', 'hezhou');
INSERT INTO `spread_area` VALUES ('714', '21', '百色', 'baise');
INSERT INTO `spread_area` VALUES ('715', '21', '河池', 'hechi');
INSERT INTO `spread_area` VALUES ('716', '21', '宜州', 'yizhou');
INSERT INTO `spread_area` VALUES ('717', '22', '琼海', 'qionghai');
INSERT INTO `spread_area` VALUES ('718', '23', '自贡', 'zigong');
INSERT INTO `spread_area` VALUES ('719', '23', '攀枝花', 'panzhihua');
INSERT INTO `spread_area` VALUES ('720', '23', '广元', 'guangyuan');
INSERT INTO `spread_area` VALUES ('721', '23', '内江', 'neijiang');
INSERT INTO `spread_area` VALUES ('722', '23', '乐山', 'leshan');
INSERT INTO `spread_area` VALUES ('723', '23', '宜宾', 'yibin');
INSERT INTO `spread_area` VALUES ('724', '23', '广安', 'guangan');
INSERT INTO `spread_area` VALUES ('725', '23', '达川', 'dachuan');
INSERT INTO `spread_area` VALUES ('726', '23', '雅安', 'yaan');
INSERT INTO `spread_area` VALUES ('727', '23', '眉山', 'meishan');
INSERT INTO `spread_area` VALUES ('728', '23', '甘孜', 'ganzi');
INSERT INTO `spread_area` VALUES ('729', '23', '凉山', 'liangshan');
INSERT INTO `spread_area` VALUES ('730', '23', '泸州', 'luzhou');
INSERT INTO `spread_area` VALUES ('731', '23', '遂宁', 'suining');
INSERT INTO `spread_area` VALUES ('732', '23', '西昌', 'xichang');
INSERT INTO `spread_area` VALUES ('733', '23', '资阳', 'ziyang');
INSERT INTO `spread_area` VALUES ('734', '23', '峨眉山', 'emeishan');
INSERT INTO `spread_area` VALUES ('735', '23', '巴中', 'bazhong');
INSERT INTO `spread_area` VALUES ('736', '23', '绵竹', 'mianzhu');
INSERT INTO `spread_area` VALUES ('737', '23', '荣县', 'rongxian');
INSERT INTO `spread_area` VALUES ('738', '23', '武侯', 'wuhou');
INSERT INTO `spread_area` VALUES ('739', '23', '阿坝', 'aba');
INSERT INTO `spread_area` VALUES ('740', '24', '六盘水', 'liupanshui');
INSERT INTO `spread_area` VALUES ('741', '24', '遵义', 'zunyi');
INSERT INTO `spread_area` VALUES ('742', '24', '安顺', 'anshun');
INSERT INTO `spread_area` VALUES ('743', '24', '铜仁', 'tongren');
INSERT INTO `spread_area` VALUES ('744', '24', '黔东南', 'qiandongnan');
INSERT INTO `spread_area` VALUES ('745', '24', '黔南', 'qiannan');
INSERT INTO `spread_area` VALUES ('746', '24', '黔西南', 'qianxinan');
INSERT INTO `spread_area` VALUES ('747', '24', '毕节', 'bijie');
INSERT INTO `spread_area` VALUES ('748', '24', '兴义', 'xingyi');
INSERT INTO `spread_area` VALUES ('749', '24', '都匀', 'duyun');
INSERT INTO `spread_area` VALUES ('750', '24', '凯里', 'kaili');
INSERT INTO `spread_area` VALUES ('751', '25', '大理', 'dali');
INSERT INTO `spread_area` VALUES ('752', '25', '玉溪', 'yuxi');
INSERT INTO `spread_area` VALUES ('753', '25', '昭通', 'zhaotong');
INSERT INTO `spread_area` VALUES ('754', '25', '楚雄', 'chuxiong');
INSERT INTO `spread_area` VALUES ('755', '25', '红河', 'honghe');
INSERT INTO `spread_area` VALUES ('756', '25', '文山', 'wenshan');
INSERT INTO `spread_area` VALUES ('757', '25', '思茅', 'simao');
INSERT INTO `spread_area` VALUES ('758', '25', '西双版纳', 'xishuangbanna');
INSERT INTO `spread_area` VALUES ('759', '25', '保山', 'baoshan');
INSERT INTO `spread_area` VALUES ('760', '25', '德宏', 'dehong');
INSERT INTO `spread_area` VALUES ('761', '25', '丽江', 'lijiang');
INSERT INTO `spread_area` VALUES ('762', '25', '怒江', 'nujiang');
INSERT INTO `spread_area` VALUES ('763', '25', '迪庆', 'diqing');
INSERT INTO `spread_area` VALUES ('764', '25', '临沧', 'lincang');
INSERT INTO `spread_area` VALUES ('765', '25', '开远', 'kaiyuan');
INSERT INTO `spread_area` VALUES ('766', '25', '个旧', 'gejiu');
INSERT INTO `spread_area` VALUES ('767', '25', '潞西', 'luxi');
INSERT INTO `spread_area` VALUES ('768', '25', '州芒', 'zhoumang');
INSERT INTO `spread_area` VALUES ('769', '27', '铜川', 'tongchuan');
INSERT INTO `spread_area` VALUES ('770', '27', '延安', 'yanan');
INSERT INTO `spread_area` VALUES ('771', '27', '汉中', 'hanzhong');
INSERT INTO `spread_area` VALUES ('772', '27', '安康', 'ankang');
INSERT INTO `spread_area` VALUES ('773', '27', '商洛', 'shangluo');
INSERT INTO `spread_area` VALUES ('774', '27', '韩城', 'hancheng');
INSERT INTO `spread_area` VALUES ('775', '28', '嘉峪关', 'jiayuguan');
INSERT INTO `spread_area` VALUES ('776', '28', '金昌', 'jinchang');
INSERT INTO `spread_area` VALUES ('777', '28', '白银', 'baiyin');
INSERT INTO `spread_area` VALUES ('778', '28', '天水', 'tianshui');
INSERT INTO `spread_area` VALUES ('779', '28', '酒泉', 'jiuquan');
INSERT INTO `spread_area` VALUES ('780', '28', '张掖', 'zhangye');
INSERT INTO `spread_area` VALUES ('781', '28', '武威', 'wuwei');
INSERT INTO `spread_area` VALUES ('782', '28', '定西', 'dingxi');
INSERT INTO `spread_area` VALUES ('783', '28', '陇南', 'longnan');
INSERT INTO `spread_area` VALUES ('784', '28', '平凉', 'pingliang');
INSERT INTO `spread_area` VALUES ('785', '28', '庆阳', 'qingyang');
INSERT INTO `spread_area` VALUES ('786', '28', '临夏', 'linxia');
INSERT INTO `spread_area` VALUES ('787', '28', '甘南', 'gannan2');
INSERT INTO `spread_area` VALUES ('788', '28', '合作', 'hezuo');
INSERT INTO `spread_area` VALUES ('789', '28', '凉州', 'liangzhou');
INSERT INTO `spread_area` VALUES ('790', '28', '静宁', 'jingning');
INSERT INTO `spread_area` VALUES ('791', '28', '武都', 'wudu');
INSERT INTO `spread_area` VALUES ('792', '28', '西峰', 'xifeng');
INSERT INTO `spread_area` VALUES ('793', '29', '石嘴山', 'shizuishan');
INSERT INTO `spread_area` VALUES ('794', '29', '吴忠', 'wuzhong');
INSERT INTO `spread_area` VALUES ('795', '29', '固原', 'guyuan');
INSERT INTO `spread_area` VALUES ('796', '30', '海东', 'haidong');
INSERT INTO `spread_area` VALUES ('797', '30', '海南', 'hainan2');
INSERT INTO `spread_area` VALUES ('798', '30', '海西', 'haixi');
INSERT INTO `spread_area` VALUES ('799', '30', '海北', 'haibei');
INSERT INTO `spread_area` VALUES ('800', '30', '黄南', 'huangnan');
INSERT INTO `spread_area` VALUES ('801', '30', '玉树', 'yushu');
INSERT INTO `spread_area` VALUES ('802', '30', '果洛', 'guoluo');
INSERT INTO `spread_area` VALUES ('803', '30', '格尔木', 'geermu');
INSERT INTO `spread_area` VALUES ('804', '31', '石河子', 'shihezi');
INSERT INTO `spread_area` VALUES ('805', '31', '克拉玛依', 'kelamayi');
INSERT INTO `spread_area` VALUES ('806', '31', '伊犁', 'yili');
INSERT INTO `spread_area` VALUES ('807', '31', '巴音郭勒', 'bayinguole');
INSERT INTO `spread_area` VALUES ('808', '31', '昌吉', 'changji');
INSERT INTO `spread_area` VALUES ('809', '31', '克孜勒苏柯尔INSE克孜', 'kezilesukeerkezi');
INSERT INTO `spread_area` VALUES ('810', '31', '博尔塔拉', 'boertala');
INSERT INTO `spread_area` VALUES ('811', '31', '吐鲁番', 'tulufan');
INSERT INTO `spread_area` VALUES ('812', '31', '哈密', 'hami');
INSERT INTO `spread_area` VALUES ('813', '31', '喀什', 'kashi');
INSERT INTO `spread_area` VALUES ('814', '31', '和田', 'hetian');
INSERT INTO `spread_area` VALUES ('815', '31', '阿克苏', 'akesu');
INSERT INTO `spread_area` VALUES ('816', '31', '库尔勒', 'kuerle');
INSERT INTO `spread_area` VALUES ('817', '31', '奎屯', 'kuitun');
INSERT INTO `spread_area` VALUES ('818', '31', '伊宁', 'yining');
INSERT INTO `spread_area` VALUES ('819', '31', '博乐', 'bole');
INSERT INTO `spread_area` VALUES ('820', '31', '乌市', 'wushi');
INSERT INTO `spread_area` VALUES ('821', '31', '塔城', 'tacheng');
INSERT INTO `spread_area` VALUES ('822', '31', '巴州库尔勒', 'bazhoukuerle');
INSERT INTO `spread_area` VALUES ('823', '31', '阿勒泰', 'aletai');
INSERT INTO `spread_area` VALUES ('825', '31', '阿图什', 'atushi');
INSERT INTO `spread_area` VALUES ('826', '12', '台州', 'taizhou2');
INSERT INTO `spread_area` VALUES ('827', '18', '丹江口', 'danjiangkou');
INSERT INTO `spread_area` VALUES ('828', '33', '台北', 'taibei');
INSERT INTO `spread_area` VALUES ('829', '33', '高雄', 'gaoxiong');
INSERT INTO `spread_area` VALUES ('830', '33', '基隆', 'jilong');
INSERT INTO `spread_area` VALUES ('831', '33', '台中', 'taizhong');
INSERT INTO `spread_area` VALUES ('832', '33', '台南', 'tainan');
INSERT INTO `spread_area` VALUES ('833', '33', '新竹', 'xinzhu');
INSERT INTO `spread_area` VALUES ('834', '33', '嘉义', 'jiayi');
INSERT INTO `spread_area` VALUES ('835', '34', '中西', '');
INSERT INTO `spread_area` VALUES ('836', '34', '湾仔', '');
INSERT INTO `spread_area` VALUES ('837', '34', '东', '');
INSERT INTO `spread_area` VALUES ('838', '34', '南', '');
INSERT INTO `spread_area` VALUES ('839', '34', '油尖旺', '');
INSERT INTO `spread_area` VALUES ('840', '34', '深水埗', '');
INSERT INTO `spread_area` VALUES ('841', '34', '九龙城区', '');
INSERT INTO `spread_area` VALUES ('842', '34', '黄大仙', '');
INSERT INTO `spread_area` VALUES ('843', '34', '观塘', '');
INSERT INTO `spread_area` VALUES ('844', '34', '北', '');
INSERT INTO `spread_area` VALUES ('845', '34', '大埔区', '');
INSERT INTO `spread_area` VALUES ('846', '34', '沙田', '');
INSERT INTO `spread_area` VALUES ('847', '34', '西贡', '');
INSERT INTO `spread_area` VALUES ('848', '34', '荃湾', '');
INSERT INTO `spread_area` VALUES ('849', '34', '屯门', '');
INSERT INTO `spread_area` VALUES ('850', '34', '元朗', '');
INSERT INTO `spread_area` VALUES ('851', '34', '葵青', '');
INSERT INTO `spread_area` VALUES ('852', '34', '离岛', '');
INSERT INTO `spread_area` VALUES ('853', '35', '花地玛堂', '');
INSERT INTO `spread_area` VALUES ('854', '35', '市圣安多尼堂', '');
INSERT INTO `spread_area` VALUES ('855', '35', '大堂', '');
INSERT INTO `spread_area` VALUES ('856', '35', '望德堂', '');
INSERT INTO `spread_area` VALUES ('857', '35', '风顺堂', '');
INSERT INTO `spread_area` VALUES ('858', '35', '嘉模堂', '');
INSERT INTO `spread_area` VALUES ('859', '35', '圣方济各堂', '');




INSERT INTO `spread_recommend` VALUES ('1', '100', '幻灯片展示', '大图展示', '5', '5', '100', '2013-12-11 11:06:28');
INSERT INTO `spread_recommend` VALUES ('2', '201', '首页第一位置', '首页第一行', '3', '3', '0', '2013-11-27 15:08:06');
INSERT INTO `spread_recommend` VALUES ('3', '202', '首页第二位置', '首页第二行', '3', '3', '0', '2013-11-27 15:08:06');
INSERT INTO `spread_recommend` VALUES ('4', '203', '首页第三位置', '首页第三行', '3', '3', '0', '2013-11-27 15:08:06');
INSERT INTO `spread_recommend` VALUES ('5', '100', '首页banner', '大图', '5', '5', '100', '2013-12-16 10:36:46');




INSERT INTO `spread_info_class` VALUES(0,'全部微信','全部微信',0);
INSERT INTO `spread_info_class` VALUES(10000,'资讯阅读','资讯阅读',0);
INSERT INTO `spread_info_class` VALUES(10001,'体育','体育',10000);
INSERT INTO `spread_info_class` VALUES(10002,'公益','公益',10000);
INSERT INTO `spread_info_class` VALUES(10003,'IT','IT',10000);
INSERT INTO `spread_info_class` VALUES(10004,'媒体','媒体',10000);
INSERT INTO `spread_info_class` VALUES(10005,'新闻','新闻',10000);
INSERT INTO `spread_info_class` VALUES(10006,'科技','科技',10000);
INSERT INTO `spread_info_class` VALUES(10007,'汽车','汽车',10000);
INSERT INTO `spread_info_class` VALUES(10008,'女性','女性',10000);
INSERT INTO `spread_info_class` VALUES(10009,'综合','综合',10000);
INSERT INTO `spread_info_class` VALUES(10010,'小说','小说',10000);
INSERT INTO `spread_info_class` VALUES(10011,'房产','房产',10000);
INSERT INTO `spread_info_class` VALUES(10012,'财经','财经',10000);
INSERT INTO `spread_info_class` VALUES(10013,'科技','科技',20000);
INSERT INTO `spread_info_class` VALUES(20000,'名人明星','名人明星',0);
INSERT INTO `spread_info_class` VALUES(20001,'文化','文化',20000);
INSERT INTO `spread_info_class` VALUES(20002,'时尚','时尚',20000);
INSERT INTO `spread_info_class` VALUES(20003,'教育','教育',20000);
INSERT INTO `spread_info_class` VALUES(20004,'演员','演员',20000);
INSERT INTO `spread_info_class` VALUES(20005,'歌手','歌手',20000);
INSERT INTO `spread_info_class` VALUES(20006,'模特','模特',20000);
INSERT INTO `spread_info_class` VALUES(20007,'体育','体育',20000);
INSERT INTO `spread_info_class` VALUES(30000,'生活购物','生活购物',0);
INSERT INTO `spread_info_class` VALUES(30001,'购物','购物',30000);
INSERT INTO `spread_info_class` VALUES(30002,'家居','家居',30000);
INSERT INTO `spread_info_class` VALUES(30003,'时尚','时尚',30000);
INSERT INTO `spread_info_class` VALUES(30004,'创意','创意',30000);
INSERT INTO `spread_info_class` VALUES(30005,'旅游','旅游',30000);
INSERT INTO `spread_info_class` VALUES(30006,'健康','健康',30000);
INSERT INTO `spread_info_class` VALUES(30007,'美食','美食',30000);
INSERT INTO `spread_info_class` VALUES(30008,'生活','生活',30000);
INSERT INTO `spread_info_class` VALUES(30009,'宠物','宠物',30000);
INSERT INTO `spread_info_class` VALUES(30010,'天气','天气',30000);
INSERT INTO `spread_info_class` VALUES(40000,'行业商家','行业商家',0);
INSERT INTO `spread_info_class` VALUES(40001,'房产','房产',40000);
INSERT INTO `spread_info_class` VALUES(40002,'餐饮','餐饮',40000);
INSERT INTO `spread_info_class` VALUES(40003,'美食','美食',40000);
INSERT INTO `spread_info_class` VALUES(40004,'休闲','休闲',40000);
INSERT INTO `spread_info_class` VALUES(40005,'娱乐','娱乐',40000);
INSERT INTO `spread_info_class` VALUES(40006,'汽车','汽车',40000);
INSERT INTO `spread_info_class` VALUES(40007,'亲子','亲子',40000);
INSERT INTO `spread_info_class` VALUES(40008,'美容','美容',40000);
INSERT INTO `spread_info_class` VALUES(40009,'美发','美发',40000);
INSERT INTO `spread_info_class` VALUES(40010,'购物','购物',40000);
INSERT INTO `spread_info_class` VALUES(40011,'酒店','酒店',40000);
INSERT INTO `spread_info_class` VALUES(40012,'健身','健身',40000);
INSERT INTO `spread_info_class` VALUES(40013,'医院','医院',40000);
INSERT INTO `spread_info_class` VALUES(50000,'影音娱乐','影音娱乐',0);
INSERT INTO `spread_info_class` VALUES(50001,'美图','美图',50000);
INSERT INTO `spread_info_class` VALUES(50002,'影视','影视',50000);
INSERT INTO `spread_info_class` VALUES(50003,'音乐','音乐',50000);
INSERT INTO `spread_info_class` VALUES(50004,'搞笑','搞笑',50000);
INSERT INTO `spread_info_class` VALUES(50005,'美女','美女',50000);
INSERT INTO `spread_info_class` VALUES(50006,'动漫','动漫',50000);
INSERT INTO `spread_info_class` VALUES(50007,'星座','星座',50000);
INSERT INTO `spread_info_class` VALUES(50008,'测试','测试',50000);
INSERT INTO `spread_info_class` VALUES(50009,'语录','语录',50000);
INSERT INTO `spread_info_class` VALUES(50011,'八卦','八卦',50000);
INSERT INTO `spread_info_class` VALUES(50012,'命理','命理',50000);
INSERT INTO `spread_info_class` VALUES(60000,'交友社区','交友社区',0);
INSERT INTO `spread_info_class` VALUES(60001,'社区','社区',60000);
INSERT INTO `spread_info_class` VALUES(60002,'交友','交友',60000);
INSERT INTO `spread_info_class` VALUES(60003,'职场','职场',60000);
INSERT INTO `spread_info_class` VALUES(60004,'婚恋','婚恋',60000);
INSERT INTO `spread_info_class` VALUES(60005,'招聘','招聘',60000);
INSERT INTO `spread_info_class` VALUES(60006,'微博','微博',60000);
INSERT INTO `spread_info_class` VALUES(70000,'文化教育','文化教育',0);
INSERT INTO `spread_info_class` VALUES(70001,'读书','读书',70000);
INSERT INTO `spread_info_class` VALUES(70002,'高校','高校',70000);
INSERT INTO `spread_info_class` VALUES(70003,'外语','外语',70000);
INSERT INTO `spread_info_class` VALUES(70004,'教育','教育',70000);
INSERT INTO `spread_info_class` VALUES(70005,'历史','历史',70000);
INSERT INTO `spread_info_class` VALUES(70006,'育儿','育儿',70000);
INSERT INTO `spread_info_class` VALUES(70007,'留学','留学',70000);
INSERT INTO `spread_info_class` VALUES(80000,'其他','其他',0);
INSERT INTO `spread_info_class` VALUES(80001,'兴趣','兴趣',80000);
INSERT INTO `spread_info_class` VALUES(80002,'互联网','互联网',80000);
INSERT INTO `spread_info_class` VALUES(80003,'移动互联网','移动互联网',80000);
INSERT INTO `spread_info_class` VALUES(80004,'电商','电商',80000);
INSERT INTO `spread_info_class` VALUES(80005,'其它','其它',80000);
INSERT INTO `spread_info_class` VALUES(80006,'海外社区','海外社区',80000);
INSERT INTO `spread_info_class` VALUES(90000,'游戏','游戏',0);
INSERT INTO `spread_info_class` VALUES(90001,'网游','网游',90000);
INSERT INTO `spread_info_class` VALUES(90002,'单机','单机',90000);


INSERT INTO `spread_config` VALUES ('account_init_money', '500');
